export const languageSettings = {
    // default word : language translation
    English: {
        Settings : "Settings",
        Menu : "Menu",
        Call_Records : "Call Records",
        Appointments : "Appointments",
        Reminders : "Reminders",
        Test_Results : "Test Results",
        Messages : "Messages",
        Referrals : "Referrals",
        Visits : "Visits",
        Care_Team : "Care Team",
        Billing : "Billing",
        Make_A_Call : "Make a Call",
        Home_Page : "Home Page",
        FAQ : "FAQ",
        Find_Urgent_Care : "Find Urgent Care",
        Chat_With_Ruff : "Chat with Ruff"
    }, 
    Portuguese: {
        Settings : "Settings",
        Menu : "Menu",
        Call_Records : "Call Records",
        Appointments : "Appointments",
        Reminders : "Reminders",
        Test_Results : "Test Results",
        Messages : "Messages",
        Referrals : "Referrals",
        Visits : "Visits",
        Care_Team : "Care Team",
        Billing : "Billing",
        Make_A_Call : "Make a Call",
        Home_Page : "Home Page",
        FAQ : "FAQ",
        Find_Urgent_Care : "Find Urgent Care",
        Chat_With_Ruff : "Fala com Ruff"
    },
    Spanish: {
        Settings : "Configuraciones",
        Menu : "Menú",
        Call_Records : "Registro de llamadas",
        Appointments : "Citas",
        Reminders : "Recordatorios",
        Test_Results : "Resultados de exámenes",
        Messages : "Mensajes",
        Referrals : "Referencias",
        Care_Team : "Equipo de antención",
        Billing : "Resumen de facturación",
        Amount_Due : "Monto pendiente",
        Payment_Details : "Detalles de pago",
        Payment_Methods : "Métodos de pago",
        Make_A_Call : "Programa una llamada",
        Home_Page : "Página de inicio",
        FAQ : "FPreguntas frecuentes",
        Find_Urgent_Care : "Encuentra un Urgent Care",
        Chat_With_Ruff : "Habla con Ruff",
        Terms_and_Conditions : "Términos y condiciones",
        Welcome : "¡Bienvdenido/a!",
        My_Symptoms : "Mis sintomas",
        Medical_History : "Historia médica",
        First_Name : "Primer nombre",
        Last_Name: "Apellido",
        DOB : "Fecha de nacimiento",
        Age : "Edad",
        Phone_number : "Número de telefono",
        Password : "Contraseña",
        Log_Out : "Cerrar sesión",
        Forgot_Password : "¿Olvidó su contraseña?",
        New_User : "Paciente nuevo",
        Symptom_Progression : "Progresión de sintomas",
        Previous_Misdiagnoses : "Diagnósticos erróneos previos",
        Developmental_Milestones : "Hitos de desarrollo",
    }
}

export const API_BASE_URL = 'http://127.0.0.1:5000'