export const languageSettings = {
    // default word : language translation
    English: {
        English : "English",
        Spanish : "Español",
        Portuguese : "Portugês",
        Settings : "Settings",
        Menu : "Menu",
        Call_Records : "Call Records",
        Appointments : "Appointments",
        Reminders : "Reminders",
        Test_Results : "Test Results",
        Messages : "Messages",
        Referrals : "Referrals",
        Care_Team : "Care Team",
        Billing : "Billing",
        Amount_Due : "Amount Due",
        Payment_Details : "Payment Details",
        Payment_Methods : "Payment Methods",
        Make_A_Call : "Make a Call",
        Home: "Home",
        Back_to_Home : "Back to Home Page",
        FAQ : "FAQ",
        Find_Urgent_Care : "Find an Urgent Care",
        Chat_With_Ruff : "Chat with Ruff",
        Terms_and_Conditions : "Terms and Conditions",
        Welcome : "Welcome!",
        My_Symptoms : "My Symptoms",
        Medical_History : "Medical History",
        First_Name : "First Name",
        Last_Name: "Last Name",
        DOB : "Date of Birth",
        Age : "Age",
        Phone_number : "Phone Number",
        Password : "Password",
        Log_Out : "Log out",
        Forgot_Password : "Forgot password?",
        New_User : "New patient",
        Symptom_Progression : "Symptom progression",
        Previous_Misdiagnoses : "Previous Misdiagnoses",
        Developmental_Milestones : "Developmental Milestones",
        Find_a_Community : "Find a Community",
        First_words : "First words",
        Walking : "Walking",
        Solid_Foods : "Eating solid foods",
        Donate_Now : "Donate Now",
        Reports : "Reports",
        Initial_assessment : "Initial Assessment",
        Calls_made : "Calls Made",
        min : "min",
        Transcrpt : "Get a transcript of call",
        Jan : "January",
        Feb : "February",
        March : "March",
        April : "April",
        May : "May",
        June : "June",
        July : "July",
        August : "August",
        Sept : "September",
        Oct : "October",
        Nov : "November",
        Dec : "December",
        Active_patient : "Active patient",
        Weekly_Sessions : "Weekly sessions",
        Status : "Status",
        View_Report : "View Report",
        Summary : "Summary",
        Verification_Code : "Enter Verification Code",
        Contact_us : "Contact Us",
        Close : "Cerrar",
        Yes : "Sí",
        No : "No"
    }, 
    Portuguese: {
        English : "Ingles",
        Spanish : "Español",
        Portuguese : "Portugês",
        Settings: "Configurações",
        Menu: "Menu",
        Call_Records: "Registros de Chamadas",
        Appointments: "Consultas",
        Reminders: "Lembretes",
        Test_Results: "Resultados de Exames",
        Messages: "Mensagens",
        Referrals: "Encaminhamentos",
        Care_Team: "Equipe de Cuidados",
        Billing: "Faturamento",
        Amount_Due: "Valor Devido",
        Payment_Details: "Detalhes do Pago",
        Payment_Methods: "Métodos de Pago",
        Make_A_Call: "Fazer uma Chamada",
        Home: "Início",
        Back_to_Home: "Voltar para Início",
        FAQ: "Perguntas Frequentes",
        Find_Urgent_Care: "Encontrar Atendimento de Urgência",
        Chat_With_Ruff: "Conversar com Ruff",
        Terms_and_Conditions: "Termos e Condições",
        Welcome: "Bem-vindo!",
        My_Symptoms: "Meus Sintomas",
        Medical_History: "História Médica",
        First_Name: "Nome",
        Last_Name: "Sobrenome",
        DOB: "Data de Nascimento",
        Age: "Idade",
        Phone_number: "Número de Telefone",
        Password: "Senha",
        Log_Out: "Sair",
        Forgot_Password: "Esqueceu a senha?",
        New_User: "Novo paciente",
        Symptom_Progression: "Progressão dos Sintomas",
        Previous_Misdiagnoses: "Diagnósticos Errôneos Anteriores",
        Developmental_Milestones: "Marcos do Desenvolvimento",
        Find_a_Community: "Encontrar uma Comunidade",
        First_words: "Primeiras palavras",
        Walking: "Andar",
        Solid_Foods: "Alimentação sólida",
        Donate_Now: "Doe Agora",
        Reports: "Relatórios",
        Initial_assessment: "Avaliação Inicial",
        Calls_made: "Chamadas Realizadas",
        min: "minutos",
        Transcrpt: "Obter transcrição da chamada",
        Jan: "Janeiro",
        Feb: "Fevereiro",
        March: "Março",
        April: "Abril",
        May: "Maio",
        June: "Junho",
        July: "Julho",
        August: "Agosto",
        Sept: "Setembro",
        Oct: "Outubro",
        Nov: "Novembro",
        Dec: "Dezembro",
        Active_patient: "Paciente ativo",
        Weekly_Sessions: "Sessões semanais",
        Status: "Status",
        View_Report: "Ver Relatório",
        Summary: "Resumo",
        Verification_Code: "Código de Verificação",
        Contact_us: "Fale Conosco",
        Close: "Fechar",
        Yes: "Sim",
        No: "Não"
    },
    Spanish: {
        English : "English",
        Spanish : "Español",
        Portuguese : "Portugês",
        Settings : "Configuraciones",
        Menu : "Menú",
        Call_Records : "Registro de llamadas",
        Appointments : "Citas",
        Reminders : "Recordatorios",
        Test_Results : "Resultados de exámenes",
        Messages : "Mensajes",
        Referrals : "Referencias",
        Care_Team : "Equipo de antención",
        Billing : "Resumen de facturación",
        Amount_Due : "Monto pendiente",
        Payment_Details : "Detalles de pago",
        Payment_Methods : "Métodos de pago",
        Make_A_Call : "Programa una llamada",
        Home: "Página de inicio",
        Back_to_Home : "Regresa a página de inicio",
        FAQ : "Preguntas frecuentes",
        Find_Urgent_Care : "Encuentra un Urgent Care",
        Chat_With_Ruff : "Habla con Ruff",
        Terms_and_Conditions : "Términos y condiciones",
        Welcome : "¡Bienvdenido/a!",
        My_Symptoms : "Mis sintomas",
        Medical_History : "Historia médica",
        First_Name : "Primer nombre",
        Last_Name: "Apellido",
        DOB : "Fecha de nacimiento",
        Age : "Edad",
        Phone_number : "Número de telefono",
        Password : "Contraseña",
        Log_Out : "Cerrar sesión",
        Forgot_Password : "¿Olvidó su contraseña?",
        New_User : "Paciente nuevo",
        Symptom_Progression : "Progresión de sintomas",
        Previous_Misdiagnoses : "Diagnósticos erróneos previos",
        Developmental_Milestones : "Hitos de desarrollo",
        Find_a_Community : "Encuentra una communidaddo",
        First_words : "Primeras palabras",
        Walking : "Caminando",
        Solid_Foods : "Comidas solidas",
        Donate_Now : "Dona ahora",
        Reports : "Reportes",
        Initial_assessment : "Evaluación inicial",
        Calls_made : "Llamadas iniciadas",
        min : "minutos",
        Transcrpt : "Recibe una transcripción de la llamada",
        Jan : "Enero",
        Feb : "Febrero",
        March : "Marzo",
        April : "Abril",
        May : "Mayo",
        June : "Junio",
        July : "Julio",
        August : "Agosto",
        Sept : "Septiembre",
        Oct : "Octubre",
        Nov : "Noviembre",
        Dec : "Diciembre",
        Active_patient : "Peciente activo",
        Weekly_Sessions : "Sesiones semanales",
        Status : "Estado",
        View_Report : "Ver reporte",
        Summary : "Sumario",
        Verification_Code : "Entra código de verificación",
        Contact_us : "Contáctanos", 
        Close : "Cerrar",
        Yes : "Sí",
        No : "No"
        
    }
}

export const API_BASE_URL = 'http://127.0.0.1:5001'