export const languageSettings = {
    // default word : language translation
    English: {
        Settings : "Settings",
        Menu : "Menu",
        Call_Records : "Call Records",
        Appointments : "Appointments",
        Reminders : "Reminders",
        Test_Results : "Test Results",
        Messages : "Messages",
        Referrals : "Referrals",
        Care_Team : "Care Team",
        Billing : "Billing",
        Amount_Due : "Amount Due",
        Payment_Details : "Payment Details",
        Payment_Methods : "Payment Methods",
        Make_A_Call : "Make a Call",
        Home_Page : "Home Page",
        Back_to_Home : "Back to Home Page",
        FAQ : "FAQ",
        Find_Urgent_Care : "Find an Urgent Care",
        Chat_With_Ruff : "Chat with Ruff",
        Terms_and_Conditions : "Terms and Conditions",
        Welcome : "Welcome!",
        My_Symptoms : "My Symptoms",
        Medical_History : "Medical History",
        First_Name : "First Name",
        Last_Name: "Last Name",
        DOB : "Date of Birth",
        Age : "Age",
        Phone_number : "Phone Number",
        Password : "Password",
        Log_Out : "Log out",
        Forgot_Password : "Forgot password?",
        New_User : "New patient",
        Symptom_Progression : "Symptom progression",
        Previous_Misdiagnoses : "Previous Misdiagnoses",
        Developmental_Milestones : "Developmental Milestones",
        Find_a_Community : "Find a Community",
        First_words : "First words",
        Walking : "Walking",
        Solid_Foods : "Eating solid foods",
        Donate_Now : "Donate Now"
    }, 
    Portuguese: {
        Settings : "Settings",
        Menu : "Menu",
        Call_Records : "Call Records",
        Appointments : "Appointments",
        Reminders : "Reminders",
        Test_Results : "Test Results",
        Messages : "Messages",
        Referrals : "Referrals",
        Visits : "Visits",
        Care_Team : "Care Team",
        Billing : "Billing",
        Make_A_Call : "Make a Call",
        Home_Page : "Home Page",
        FAQ : "FAQ",
        Find_Urgent_Care : "Find Urgent Care",
        Chat_With_Ruff : "Fala com Ruff"
    },
    Spanish: {
        English : "English",
        Spanish : "Español",
        Portuguese : "Portugês",
        Settings : "Configuraciones",
        Menu : "Menú",
        Call_Records : "Registro de llamadas",
        Appointments : "Citas",
        Reminders : "Recordatorios",
        Test_Results : "Resultados de exámenes",
        Messages : "Mensajes",
        Referrals : "Referencias",
        Care_Team : "Equipo de antención",
        Billing : "Resumen de facturación",
        Amount_Due : "Monto pendiente",
        Payment_Details : "Detalles de pago",
        Payment_Methods : "Métodos de pago",
        Make_A_Call : "Programa una llamada",
        Home_Page : "Página de inicio",
        Back_to_Home : "Regresa a página de inicio",
        FAQ : "Preguntas frecuentes",
        Find_Urgent_Care : "Encuentra un Urgent Care",
        Chat_With_Ruff : "Habla con Ruff",
        Terms_and_Conditions : "Términos y condiciones",
        Welcome : "¡Bienvdenido/a!",
        My_Symptoms : "Mis sintomas",
        Medical_History : "Historia médica",
        First_Name : "Primer nombre",
        Last_Name: "Apellido",
        DOB : "Fecha de nacimiento",
        Age : "Edad",
        Phone_number : "Número de telefono",
        Password : "Contraseña",
        Log_Out : "Cerrar sesión",
        Forgot_Password : "¿Olvidó su contraseña?",
        New_User : "Paciente nuevo",
        Symptom_Progression : "Progresión de sintomas",
        Previous_Misdiagnoses : "Diagnósticos erróneos previos",
        Developmental_Milestones : "Hitos de desarrollo",
        Find_a_Community : "Encuentra una communidaddo",
        First_words : "Primeras palabras",
        Walking : "Caminando",
        Solid_Foods : "Comidas solidas",
        Donate_Now : "Dona ahora",
        Reports : "Reportes",
        Initial_assessment : "Evaluación inicial",
        Calls_made : "Llamadas iniciadas",
        min : "minutos",
        Transcrpt : "Recibe una transcripción de la llamada",
        Jan : "Enero",
        Feb : "Febrero",
        March : "Marzo",
        April : "Abril",
        May : "Mayo",
        June : "Junio",
        July : "Julio",
        August : "Agosto",
        Sept : "Septiembre",
        Oct : "Octubre",
        Nov : "Noviembre",
        Dec : "Diciembre",
        Active_patient : "Peciente activo",
        Weekly_Sessions : "Sesiones semanales",
        Status : "Estado",
        View_Report : "Ver reporte",
        Summary : "Sumario"
    }
}

export const API_BASE_URL = 'http://127.0.0.1:5001'